name: mlops-workshop

channels:
    - conda-forge

dependencies:
  - pip
  - pip:
    - tensorflow
  - python
  - scikit-learn
  - pandas
  - seaborn
  - jupyter
  - notebook
  - numpy
  - matplotlib
  - evidently
  - prometheus_client
  - mlflow
  - Flask
  - Werkzeug
  - requests
  - pyyaml
