name: mlops-workshop

channels:
    - conda-forge

dependencies:
  - python
  - scikit-learn
  - pandas
  - seaborn
  - jupyter
  - tensorflow
  - notebook
  - numpy
  - matplotlib
  - evidently
  - prometheus_client